### ISSUE TITLE
Error: Type 'DiagnosticableMixin' not found.

### ISSUE THREAD

**Issue by KeepUpCode** [md-weber/buy_me_a_coffee#2]
I get this error.
```
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
```
Mybe should upgrade flutter_svg package.

**Comment by DanXCVII** [comment]
You are right. A version update of flutter_svg to 0.19.1 should fix the issue. Unfortunately can't use the package now.

**Comment by md-weber** [comment]
I will work on it today so that it will be available around tomorrow.

**Comment by md-weber** [comment]
Should be solved now and is already updated in pub.dev
