### ISSUE TITLE
Move default branch from master to main

### ISSUE THREAD

**Issue by hemish11** [md-weber/buy_me_a_coffee#7]
Recently, Github has changed the master branch to main, so we should also take this step and change the branch of a flutter from master to main.

Here are all the commands that need to run to make a clone of this branch with a different name:
`git branch -m master main`
`git push -u origin main`
`git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main`

After all this, we need to change the default branch from the settings of the repo.

And finally, run this command to delete the master branch
`git push origin --delete master`

Thanks a lot.

**Comment by md-weber** [comment]
Great idea, I will do that. Sorry that I only react now somehow I did not get a notification.

**Comment by hemish11** [comment]
No problem, sometimes, I also don't get notifications from Github. So, do I close this issue?

**Comment by md-weber** [comment]
I just renamed the default branch. I guess that should do the trick 👍 - I close this PR now.
