### ISSUE TITLE
Add linting rules to the package

### ISSUE THREAD

**Issue by md-weber** [md-weber/buy_me_a_coffee#9]
In the Pull Request https://github.com/md-weber/buy_me_a_coffee/pull/8 we had minor fixed and it would be beneficial to add some linting rules. We have two paths that we can do here.

1. Add the Lint package 🚀
2. Add the rules for prefer const etc. 👍 

If you have a strong preference please use the icon above on this issue so we can fix accordingly.

**Comment by Abhishek01039** [comment]
https://pub.dev/packages/pedantic
what do you think about this? @md-weber

**Comment by md-weber** [comment]
I like the pedantic package but it is pretty hard aligned to the Flutter Repository needs. As a bit more "developer" friendly I currently prefer the lint package.
https://pub.dev/packages/lint

**Comment by Abhishek01039** [comment]
Great!!
Please go ahead.
